
function updateRender(){
    if(keyStatus["leftArrow"]){
        moveCamera("left");
        //camera.translateX(-0.3);
    }
    if(keyStatus["rightArrow"]){
        moveCamera("right");
        //camera.translateX(0.3);
    }
    if(keyStatus["upArrow"]){
        moveCamera("forward");
        //camera.translateY(0.3);
        //camera.translateZ(-0.3);
    }
    if(keyStatus["downArrow"]){
        moveCamera("backward");
        //camera.translateY(-0.3);
        //camera.translateZ(0.3);
    }
    if(keyStatus["qKey"]){
        rotateCamera("counterclockwise");
    }
    if(keyStatus["eKey"]){
        rotateCamera("clockwise");
    }
    if(keyStatus["oKey"]){
        zoomCamera("forward");
        //camera.translateZ(-0.3);     
    }
    
    if(keyStatus["pKey"]){
        zoomCamera("backward");
        //camera.translateZ(0.3);
    }
    
    if(movementUnlocked){
        if(keyStatus["wKey"]){
            //cursorForward();
            cursorMove("forward");
        }
        if(keyStatus["aKey"]){
            //cursorLeft();
            cursorMove("left");
        }
        if(keyStatus["sKey"]){
            //cursorBackward();
            cursorMove("backward");
        }
        if(keyStatus["dKey"]){
            //cursorRight();
            cursorMove("right");
        }
        if(keyStatus["enter"]){
            followCursor();
        }
        if(keyStatus["space"]){
            //moveEnemy();
        }
    }
    readGrid(cursor_currentPos, currentPos, range);
}